on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Push to wiki
      uses: ad-m/github-push-action@master
      with:
        # This token needs read and write access for contents on the repo with the wiki
        github_token: ${{ secrets.PAT }}
        branch: ${{ github.ref }}
        repository: Steamodded/smods.wiki
        force: true
